ingredients = input("Enter ingredients (comma separated): ").strip().lower().split(",")
ingredients = [i.strip() for i in ingredients]

if "eggs" in ingredients and "milk" in ingredients:
    print("✅ Recipe Suggestion: Omelette with eggs and milk.")
    print("How to cook:")
    print("1. Beat 2 eggs with a splash of milk.")
    print("2. Heat a pan and add some butter or oil.")
    print("3. Pour the egg mixture and cook until done.")
elif "tomato" in ingredients and "pasta" in ingredients:
    print("✅ Recipe Suggestion: Pasta with tomato sauce.")
    print("How to cook:")
    print("1. Boil pasta until soft.")
    print("2. Cook chopped tomatoes with garlic and olive oil.")
    print("3. Mix pasta and sauce, then serve.")
elif "potato" in ingredients and "oil" in ingredients:
    print("✅ Recipe Suggestion: Crispy potato fries.")
    print("How to cook:")
    print("1. Cut potatoes into sticks.")
    print("2. Heat oil in a deep pan.")
    print("3. Fry potato sticks until golden and crispy.")
elif "chicken" in ingredients and "rice" in ingredients:
    print("✅ Recipe Suggestion: Chicken fried rice.")
    print("How to cook:")
    print("1. Cook rice and keep aside.")
    print("2. Stir-fry chicken pieces with vegetables.")
    print("3. Add rice and soy sauce, mix well and serve.")
elif "banana" in ingredients and "milk" in ingredients:
    print("✅ Recipe Suggestion: Banana smoothie.")
    print("How to cook:")
    print("1. Peel and slice the banana.")
    print("2. Blend banana with milk and honey.")
    print("3. Serve chilled.")
elif "bread" in ingredients and "butter" in ingredients:
    print("✅ Recipe Suggestion: Butter toast.")
    print("How to cook:")
    print("1. Spread butter on bread slices.")
    print("2. Toast in a pan or toaster until golden.")
    print("3. Serve warm.")
elif "rice" in ingredients and "lentils" in ingredients:
    print("✅ Recipe Suggestion: Rice and dal.")
    print("How to cook:")
    print("1. Cook rice separately.")
    print("2. Boil lentils with turmeric and salt.")
    print("3. Serve lentils over rice.")
elif "flour" in ingredients and "sugar" in ingredients and "egg" in ingredients:
    print("✅ Recipe Suggestion: Basic pancakes.")
    print("How to cook:")
    print("1. Mix flour, sugar, egg, and milk to make batter.")
    print("2. Heat pan and pour batter to make pancakes.")
    print("3. Cook until golden on both sides and serve.")
elif "cheese" in ingredients and "bread" in ingredients:
    print("✅ Recipe Suggestion: Grilled cheese sandwich.")
    print("How to cook:")
    print("1. Place cheese between two bread slices.")
    print("2. Grill in a pan until cheese melts and bread is golden.")
    print("3. Serve hot.")
elif "apple" in ingredients and "cinnamon" in ingredients:
    print("✅ Recipe Suggestion: Baked cinnamon apples.")
    print("How to cook:")
    print("1. Slice apples and sprinkle cinnamon.")
    print("2. Bake in oven at 180°C for 20 minutes.")
    print("3. Serve warm as dessert.")
elif "carrot" in ingredients and "peas" in ingredients:
    print("✅ Recipe Suggestion: Mixed vegetable stir fry.")
    print("How to cook:")
    print("1. Heat oil in a pan.")
    print("2. Add chopped carrots and peas, stir fry until tender.")
    print("3. Season with salt and pepper, serve hot.")
elif "chocolate" in ingredients and "milk" in ingredients:
    print("✅ Recipe Suggestion: Hot chocolate.")
    print("How to cook:")
    print("1. Heat milk in a saucepan.")
    print("2. Add chocolate and stir until melted.")
    print("3. Serve warm.")
elif "cucumber" in ingredients and "yogurt" in ingredients:
    print("✅ Recipe Suggestion: Cucumber raita.")
    print("How to cook:")
    print("1. Grate cucumber and mix with yogurt.")
    print("2. Add salt and roasted cumin powder.")
    print("3. Serve chilled as a side dish.")
elif "onion" in ingredients and "tomato" in ingredients:
    print("✅ Recipe Suggestion: Onion tomato curry.")
    print("How to cook:")
    print("1. Fry onions until golden.")
    print("2. Add chopped tomatoes and spices.")
    print("3. Cook until oil separates, serve with rice.")
elif "fish" in ingredients and "lemon" in ingredients:
    print("✅ Recipe Suggestion: Lemon grilled fish.")
    print("How to cook:")
    print("1. Marinate fish with lemon juice, salt, and pepper.")
    print("2. Grill until cooked through.")
    print("3. Serve with salad.")
elif "corn" in ingredients and "butter" in ingredients:
    print("✅ Recipe Suggestion: Buttered corn on the cob.")
    print("How to cook:")
    print("1. Boil corn until tender.")
    print("2. Spread butter and sprinkle salt.")
    print("3. Serve hot.")
elif "spinach" in ingredients and "garlic" in ingredients:
    print("✅ Recipe Suggestion: Garlic sautéed spinach.")
    print("How to cook:")
    print("1. Heat oil and sauté garlic.")
    print("2. Add spinach and cook until wilted.")
    print("3. Season with salt and serve.")
elif "oats" in ingredients and "milk" in ingredients:
    print("✅ Recipe Suggestion: Oatmeal porridge.")
    print("How to cook:")
    print("1. Boil oats in milk.")
    print("2. Add sugar or honey to taste.")
    print("3. Serve warm.")
elif "beef" in ingredients and "pepper" in ingredients:
    print("✅ Recipe Suggestion: Pepper steak.")
    print("How to cook:")
    print("1. Marinate beef with crushed pepper and salt.")
    print("2. Stir fry until cooked.")
    print("3. Serve hot with vegetables.")
elif "yogurt" in ingredients and "honey" in ingredients:
    print("✅ Recipe Suggestion: Honey yogurt dessert.")
    print("How to cook:")
    print("1. Mix yogurt and honey.")
    print("2. Add nuts or fruits if available.")
    print("3. Serve chilled.")
else:
    print("❌ Sorry, no recipe suggestions found for those ingredients.")
